function handleScoreForm(form){
	if(form.short1.value===''){
		alert('请给第一个简答题打分')
		form.short1.focus()
		return
	}
	if(form.short1.value>5||form.short1.value<0){
		alert('分值应位于0-5之间，请重新打分')
		form.short1.focus()
		return
	}
	if(form.short2.value===''){
		alert('请给第二个简答题打分')
		form.short2.focus()
		return
	}
	if(form.short2.value>5||form.short2.value<0){
		alert('分值应位于0-5之间，请重新打分')
		form.short2.focus()
		return
	}
	if(form.short3.value===''){
		alert('请给第三个简答题打分')
		form.short3.focus()
		return
	}
	if(form.short3.value>5||form.short3.value<0){
		alert('分值应位于0-5之间，请重新打分')
		form.short3.focus()
		return
	}
	if(form.short4.value===''){
		alert('请给第四个简答题打分')
		form.short4.focus()
		return
	}
	if(form.short4.value>5||form.short4.value<0){
		alert('分值应位于0-5之间，请重新打分')
		form.short4.focus()
		return
	}
	if(form.short5.value===''){
		alert('请给第五个简答题打分')
		form.short5.focus()
		return
	}
	if(form.short5.value>5||form.short5.value<0){
		alert('分值应位于0-5之间，请重新打分')
		form.short5.focus()
		return
	}
	if(form.short6.value===''){
		alert('请给第六个简答题打分')
		form.short6.focus()
		return
	}
	if(form.short6.value>10||form.short6.value<0){
		alert('分值应位于0-10之间，请重新打分')
		form.short6.focus()
		return
	}
	if(form.short7.value===''){
		alert('请给第七个简答题打分')
		form.short7.focus()
		return
	}
	if(form.short7.value>10||form.short7.value<0){
		alert('分值应位于0-10之间，请重新打分')
		form.short7.focus()
		return
	}
	if(form.short8.value===''){
		alert('请给第八个简答题打分')
		form.short8.focus()
		return
	}
	if(form.short8.value>15||form.short8.value<0){
		alert('分值应位于0-15之间，请重新打分')
		form.short8.focus()
		return
	}
	form.submit()
}
